site_name: Reflex Documentation
theme:
  name: material
  logo: img/symbol.png
  favicon: img/symbol.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
extra_css:
  - 'css/style.css'
markdown_extensions:
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.superfences 
plugins:
  - swagger-ui:
    spec_url: "swagger.json"
    outfile: "docs/api.md"
